# Generated by Django 5.0.7 on 2024-08-05 09:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherexchangelead',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
