# Generated by Django 5.0.7 on 2024-08-05 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_voucherexchangelead_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherexchangelead',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
