# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2024-07-17 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0072_voucherpaymentlead_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('voucher_pattern', models.CharField(blank=True, max_length=500, null=True)),
                ('pin_required', models.BooleanField(default=True)),
                ('min_amount', models.FloatField(blank=True, default=0, null=True)),
                ('max_amount', models.FloatField(blank=True, default=0, null=True)),
                ('fee', models.FloatField(blank=True, default=0, null=True)),
                ('comission', models.FloatField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(choices=[(b'ZAR', b'Rand'), (b'USD', b'Dollar'), (b'EUR', b'Euro')], default=b'ZAR', max_length=10)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='voucherpaymentlead',
            name='currency',
            field=models.CharField(blank=True, choices=[(b'ZAR', b'Rand'), (b'USD', b'Dollar'), (b'EUR', b'Euro')], default=b'ZAR', max_length=10, null=True),
        ),
    ]
