# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2024-07-17 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0073_auto_20240717_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherpaymentlead',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.VoucherProvider'),
        ),
    ]
