# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2024-07-17 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0074_auto_20240717_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherprovider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'uploads/%Y/%m/%d/'),
        ),
    ]
