# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2024-07-22 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0075_voucherprovider_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherprovider',
            name='conversion_duration',
            field=models.FloatField(blank=True, default=60, null=True),
        ),
    ]
