# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2024-07-22 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0076_voucherprovider_conversion_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherprovider',
            name='conversion_duration',
            field=models.IntegerField(blank=True, default=60, null=True),
        ),
    ]
