# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2024-07-23 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0077_auto_20240722_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherprovider',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
