# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2024-07-23 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0078_voucherprovider_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherprovider',
            name='company',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='voucherprovider',
            name='telephone',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='voucherprovider',
            name='website',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
