# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2024-07-25 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0079_auto_20240724_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_code', models.CharField(blank=True, max_length=150, null=True)),
                ('security_pin', models.CharField(blank=True, max_length=150, null=True)),
                ('expiary_date', models.DateTimeField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('currency', models.CharField(blank=True, choices=[(b'ZAR', b'Rand'), (b'USD', b'Dollar'), (b'EUR', b'Euro')], default=b'ZAR', max_length=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[(b'Awaiting Collection', b'Awaiting Collection'), (b'Collected', b'Collected'), (b'Pending', b'Pending'), (b'Declined', b'Declined'), (b'Canceled', b'Canceled')], default=b'Pending', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.VoucherProvider')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherExchangeLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[(b'Awaiting Collection', b'Awaiting Collection'), (b'Collected', b'Collected'), (b'Pending', b'Pending'), (b'Declined', b'Declined'), (b'Canceled', b'Canceled')], default=b'Pending', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('new_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_voucher', to='website.Voucher')),
                ('old_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_voucher', to='website.Voucher')),
                ('pocket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Pocket')),
                ('transactions', models.ManyToManyField(blank=True, to='website.Transaction')),
            ],
        ),
    ]
