# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2024-07-25 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0080_voucher_voucherexchangelead'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherexchangelead',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='voucherexchangelead',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
