# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2024-07-27 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0081_auto_20240725_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
