# Generated by Django 5.0.7 on 2024-08-04 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0082_voucher_updated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtimedepositlead',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='airtimedepositlead',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Canceled', 'Canceled')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='airtimedeposittransaction',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='airtimedeposittransaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bankdepositlead',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bankdepositlead',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Canceled', 'Canceled')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='bankpaymentlead',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bankpaymentlead',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Canceled', 'Canceled')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='claimedpromotion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='crowdcoinpaymentlead',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='crowdcoinpaymentlead',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Canceled', 'Canceled')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='callback_method',
            field=models.CharField(default='POST', max_length=100),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='callback_url',
            field=models.URLField(blank=True, default='http://', null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='subscription',
            field=models.CharField(choices=[('Trial', 'Trial'), ('Premium', 'Premium'), ('Enterprise', 'Enterprise')], default='Trial', max_length=100),
        ),
        migrations.AlterField(
            model_name='network',
            name='deposit_denominations',
            field=models.CharField(blank=True, default='5,10', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='onetimepin',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='onetimepin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pocket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pocket',
            name='voucher_receiving_fee',
            field=models.CharField(blank=True, default='0%', max_length=100),
        ),
        migrations.AlterField(
            model_name='pocket',
            name='voucher_sending_fee',
            field=models.CharField(blank=True, default='0%', max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='simcard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='simcard',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Deactivated', 'Deactivated'), ('Receiving', 'Receiving'), ('Paused', 'Paused'), ('Dispatch', 'Dispatch'), ('Circulating', 'Circulating')], default='New', max_length=100),
        ),
        migrations.AlterField(
            model_name='smsinbound',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='smsinbound',
            name='is_read',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='smsinbound',
            name='replied',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='smsoutbound',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='smsoutbound',
            name='is_dispatched',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='uniqueidentifier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pin',
            field=models.CharField(blank=True, default='0000', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='currency',
            field=models.CharField(blank=True, choices=[('ZAR', 'Rand'), ('USD', 'Dollar'), ('EUR', 'Euro')], default='ZAR', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Awaiting Collection', 'Awaiting Collection'), ('Collected', 'Collected'), ('Pending', 'Pending'), ('Declined', 'Declined'), ('Canceled', 'Canceled')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='voucherexchangelead',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='voucherexchangelead',
            name='status',
            field=models.CharField(choices=[('Awaiting Collection', 'Awaiting Collection'), ('Collected', 'Collected'), ('Pending', 'Pending'), ('Declined', 'Declined'), ('Canceled', 'Canceled')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='voucherpaymentlead',
            name='currency',
            field=models.CharField(blank=True, choices=[('ZAR', 'Rand'), ('USD', 'Dollar'), ('EUR', 'Euro')], default='ZAR', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='voucherpaymentlead',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='voucherpaymentlead',
            name='status',
            field=models.CharField(choices=[('Awaiting Collection', 'Awaiting Collection'), ('Collected', 'Collected'), ('Pending', 'Pending'), ('Declined', 'Declined'), ('Canceled', 'Canceled')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='voucherprovider',
            name='currency',
            field=models.CharField(choices=[('ZAR', 'Rand'), ('USD', 'Dollar'), ('EUR', 'Euro')], default='ZAR', max_length=10),
        ),
        migrations.AlterField(
            model_name='voucherprovider',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='voucherprovider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
