# Generated by Django 5.0.7 on 2024-08-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0002_conversation_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('template', models.JSONField()),
            ],
        ),
    ]
