# Generated by Django 5.0.7 on 2024-08-06 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiUSSD', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='return_node',
        ),
        migrations.AddField(
            model_name='campaign',
            name='starting_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_starting_node', to='MiUSSD.node'),
        ),
        migrations.CreateModel(
            name='NodeResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_response', models.CharField(max_length=255)),
                ('next_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_responses', to='MiUSSD.node')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='MiUSSD.node')),
            ],
        ),
    ]
