# Generated by Django 5.0.7 on 2024-08-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiUSSD', '0002_remove_node_return_node_campaign_starting_node_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='session_end',
            field=models.BooleanField(default=False),
        ),
    ]
